SELECT 
     m.MEMBER_NBR
    ,aw.ACCOUNT_NBR
	,1 = CASE WHEN aw.WARNING_CODE = 1 THEN 'Y' ELSE 'N' END
	,5 = CASE WHEN aw.WARNING_CODE = 5 THEN 'Y' ELSE 'N' END
	,11 = CASE WHEN aw.WARNING_CODE = 11 THEN 'Y' ELSE 'N' END
	,12 = CASE WHEN aw.WARNING_CODE = 12 THEN 'Y' ELSE 'N' END
	,13 = CASE WHEN aw.WARNING_CODE = 13 THEN 'Y' ELSE 'N' END
	,15 = CASE WHEN aw.WARNING_CODE = 15 THEN 'Y' ELSE 'N' END
	,16 = CASE WHEN aw.WARNING_CODE = 16 THEN 'Y' ELSE 'N' END
	,20 = CASE WHEN aw.WARNING_CODE = 20 THEN 'Y' ELSE 'N' END
	,ALERT = CASE WHEN aw.IS_SBA_ALERT = NULL THEN 'N' ELSE 'Y' END

FROM  
MEMBERSHIP m

INNER JOIN ACCOUNTWARNING aw
    on aw.MEMBER_NBR = m.MEMBER_NBR and aw.WARNING_CODE in (2,4,6,7,8,9,10,14,17,18,19)  

INNER JOIN ACCOUNTWARNING aw 
    on aw.MEMBER_NBR = m.MEMBER_NBR and aw.WARNING_CODE in (1,5)

INNER JOIN ACCOUNTWARNING aw 
   on aw.MEMBER_NBR = m.MEMBER_NBR and aw.WARNING_CODE in (11,12,13,15,16,20)

INNER JOIN ACCOUNTWARNING aw 
   on aw.MEMBER_NBR = m.MEMBER_NBR and aw.IS_SBA_ALERT = NULL
